spring:
  application:
    name: api-gateway

---

spring:
  config:
    activate:
      on-profile: default
  cloud:
   gateway:
    routes:
       - id: user-service
         uri: lb://USER-SERVICE
         predicates:
          - Path=/api/users/**
       - id: canteen-service
         uri: lb://CANTEEN-SERVICE
         predicates:
          - Path=/api/items/**    

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---

spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: canteen-service
          uri: lb://canteen-service
          predicates:
            - Path=/canteen/**  
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

