spring:
  application:
    name: config-server
  profiles:
    active: default

---

spring:
  config:
    activate:
      on-profile: default

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vaibhavkn43/cms-config-repo
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vaibhavkn43/cms-config-repo
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
