spring:
  application:
    name: user-service

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
   url: jdbc:mysql://localhost:3306/user_service
   username: root
   password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: myLocalSecretKey123
  expiration: 3600000 # 1 hour in milliseconds
      
      
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/user_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
jwt:
  secret: myDockerSecretKey123
  expiration: 3600000 # 1 hour in milliseconds
      
