spring:
  application:
    name: user-service

---

spring:
  config:
    activate:
      on-profile: default

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/user_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
